<a href="https://colab.research.google.com/github/CharlotteY2003/MIT-Futuremakers/blob/main/7_26_Upsampling_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import *

In [13]:
X = np.asarray([[1,2],
               [3,4]])
print(X)

[[1 2]
 [3 4]]


In [14]:
X = X.reshape(1,2,2,1) #last 1 = channel dimension
#Since input is grayscale (only have 1 channel)

#Testing Upsampling layer

In [15]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1), size=(2,3), interpolation='bilinear'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_3 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [16]:
y_pred = model.predict(X) #Don't we need to compile and fit the model before prediction?
#Probably not because model is not learning (no learned parameters) that the model has to train for and only needs to double the input

In [17]:
y_pred = y_pred.reshape(4,6) #reshape output to remove channel to make printing easier
#4 x 4 output because we are doubling input for upsampling
print(y_pred)

[[1.        1.        1.3333334 1.6666667 2.        2.       ]
 [1.5       1.5       1.8333334 2.1666667 2.5       2.5      ]
 [2.5       2.5       2.8333335 3.1666667 3.5       3.5      ]
 [3.        3.        3.3333335 3.6666667 4.        4.       ]]


#Simple Generator Model with Upsampling

In [21]:
model = Sequential()
model.add(Dense(128*5*5,input_dim=100))
model.add(Reshape((5,5,128))) #128 5x5 feature maps
model.add(UpSampling2D())
#Fill in detail of the upsampled feature maps
model.add(Conv2D(1,(3,3),padding='same'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_4 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


#Conv2D Transpose Model

In [22]:
model = Sequential()
model.add(Conv2DTranspose(input_shape=(2,2,1),filters=1,kernel_size=(1,1), strides=(2,2)))
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [24]:
weights = [np.asarray([[[[1]]]]), np.asarray([0])] #Set weight to 1 and bias to 0 to have no influence
model.set_weights(weights)

In [25]:
y_pred = model.predict(X)
y_pred = y_pred.reshape(4,4)
print(y_pred)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


#Simple Generator Model With the Conv2DTranspose Layer

In [29]:
model = Sequential()
model.add(Dense(128 * 5 * 5,input_dim=100))
model.add(Reshape((5, 5, 128)))
model.add(Conv2DTranspose(1,(3,3),strides=(2,2),padding='same'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
